# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 242)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 20, 501, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.target = QtWidgets.QLabel(self.widget)
        self.target.setObjectName("target")
        self.verticalLayout_3.addWidget(self.target)
        self.splitterTarget = QtWidgets.QSplitter(self.widget)
        self.splitterTarget.setOrientation(QtCore.Qt.Horizontal)
        self.splitterTarget.setObjectName("splitterTarget")
        self.lineEditTarget = QtWidgets.QLineEdit(self.splitterTarget)
        self.lineEditTarget.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditTarget.setObjectName("lineEditTarget")
        self.toolButtonTarget = QtWidgets.QToolButton(self.splitterTarget)
        self.toolButtonTarget.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButtonTarget.setObjectName("toolButtonTarget")
        self.verticalLayout_3.addWidget(self.splitterTarget)
        self.exportDirectory = QtWidgets.QLabel(self.widget)
        self.exportDirectory.setObjectName("exportDirectory")
        self.verticalLayout_3.addWidget(self.exportDirectory)
        self.splitterExport = QtWidgets.QSplitter(self.widget)
        self.splitterExport.setOrientation(QtCore.Qt.Horizontal)
        self.splitterExport.setObjectName("splitterExport")
        self.lineEditExport = QtWidgets.QLineEdit(self.splitterExport)
        self.lineEditExport.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditExport.setObjectName("lineEditExport")
        self.toolButtonExport = QtWidgets.QToolButton(self.splitterExport)
        self.toolButtonExport.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButtonExport.setObjectName("toolButtonExport")
        self.verticalLayout_3.addWidget(self.splitterExport)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(160, 180, 191, 32))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonDecrypt = QtWidgets.QPushButton(self.widget1)
        self.pushButtonDecrypt.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonDecrypt.setObjectName("pushButtonDecrypt")
        self.horizontalLayout_2.addWidget(self.pushButtonDecrypt)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonConvert = QtWidgets.QPushButton(self.widget1)
        self.pushButtonConvert.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonConvert.setObjectName("pushButtonConvert")
        self.horizontalLayout_2.addWidget(self.pushButtonConvert)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MyDecryptPDF"))
        self.target.setText(_translate("Dialog", "目标文件："))
        self.toolButtonTarget.setText(_translate("Dialog", "..."))
        self.exportDirectory.setText(_translate("Dialog", "导出目录："))
        self.toolButtonExport.setText(_translate("Dialog", "..."))
        self.pushButtonDecrypt.setText(_translate("Dialog", "解密"))
        self.pushButtonConvert.setText(_translate("Dialog", "转换"))
